[package]
name = "asset_transformer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = "0.18"
bevy_ecs = "0.18"
bevy_asset = "0.18"
bevy_platform = "0.18"

[dev-dependencies]
bevy = "0.18"
